### PR TITLE
Ignore the default group.

### PR DESCRIPTION
**Pull request by Shylock-Hg**

### CODE REVIEW

**Review by critical27 — APPROVED** [review]

**Comment by darionyaphet** [comment]
This will not happen Because Graph has checked @critical27

**Comment by Shylock-Hg** [comment]
> This will not happen Because Graph has checked @critical27
> 
> [vesoft-inc/nebula-graph#905](https://github.com/vesoft-inc/nebula-graph/pull/905)

The show create will result `CREATE SPACE xxx ON default`, this should be execute succeeded.

**Comment by Shylock-Hg** [comment]
> > > This will not happen Because Graph has checked @critical27
> > > [vesoft-inc/nebula-graph#905](https://github.com/vesoft-inc/nebula-graph/pull/905)
> > 
> > 
> > The show create will result `CREATE SPACE xxx ON default`, this should be execute succeeded.
> 
> No if so, not need to specify the group

DESC SPACE return empty group too?

**Comment by darionyaphet** [comment]
> > > > This will not happen Because Graph has checked @critical27
> > > > [vesoft-inc/nebula-graph#905](https://github.com/vesoft-inc/nebula-graph/pull/905)
> > > 
> > > 
> > > The show create will result `CREATE SPACE xxx ON default`, this should be execute succeeded.
> > 
> > 
> > No if so, not need to specify the group
> 
> DESC SPACE return empty group too?

When the group is empty will filled with `default`

**Review by yixinglu — APPROVED** [review]
~~~~

**Comment by Shylock-Hg** [comment]
Stale

**Pull request closed without merging**
