### PR TITLE
enable and add more UT

### PR DESCRIPTION
**Pull request by panda-sheep**
1) rewrite compact ut
2) enable StorageHttpAdminHandlerTest  
    StorageHttpDownloadHandlerTest 
    StorageHttpIngestHandlerTest

### CODE REVIEW

**Comment by critical27** [comment]
Good job, vertexCacheTest could be added after #224 merged

**Comment by panda-sheep** [comment]
> Good job, vertexCacheTest could be added after #224 merged

**Comment by panda-sheep** [comment]
> Good job, vertexCacheTest could be added after #224 merged

Yeah，will  use the new pr to submit vertexCacheTest

**Review by critical27 — APPROVED** [review]
Good job

**Review by liuyu85cn — APPROVED** [review]

**Pull request merged**
