### PR TITLE
Update nebula-storaged.conf.production

### PR DESCRIPTION
**Pull request by ownthink**
更改默认配置127.0.0.1

### CODE REVIEW

**Comment by panda-sheep** [comment]
Please refer to #229

This is deliberately changed in pr 229.

**Comment by bright-starry-sky** [comment]
So could you close this PR? Anyway, thank you for your contribution.

**Comment by ownthink** [comment]
> So could you close this PR? Anyway, thank you for your contribution.

关了吧，你们whitewum叫我提交的

**Comment by bright-starry-sky** [comment]
> > So could you close this PR? Anyway, thank you for your contribution.
> 
> 关了吧，你们whitewum叫我提交的

Aha, I don't know about your previous agreement with @whitewum. If it is purposeful, please reopen it.

**Comment by bright-starry-sky** [comment]
> > So could you close this PR? Anyway, thank you for your contribution.
> 
> 关了吧，你们whitewum叫我提交的

Aha, I don't know about your previous agreement with @whitewum. If it is purposeful, please reopen it.

**Pull request closed without merging**
