### PR TITLE
Added validity check for timestamp default value and more test

### PR DESCRIPTION
**Pull request by laura-ding**
Closes [NG-356]

depends on https://github.com/vesoft-inc/nebula-common/pull/369

### CODE REVIEW

**Review by dutor — DISMISSED** [review]

**Review by Shylock-Hg — DISMISSED** [review]

**Review by critical27 — DISMISSED** [review]
LGTM

**Comment by critical27** [comment]
@laura-ding, fail to compile

**Comment by laura-ding** [comment]
> @laura-ding, fail to compile

depends on common pr

**Comment by critical27** [comment]
> @laura-ding, fail to compile

👌

**Review by dutor — APPROVED** [review]

**Review by dutor — APPROVED** [review]

**Review by yixinglu — APPROVED** [review]

**Pull request merged**
