### PR TITLE
Storage CI build stability

### PR DESCRIPTION
**Pull request by bright-starry-sky**
CI tests often fail during link object on system on ubuntu1804-gcc-9.2, often are OOM errors.

```
Scanning dependencies of target processor_test

620[ 74%] Building CXX object src/meta/test/CMakeFiles/processor_test.dir/ProcessorTest.cpp.o

621[ 75%] Linking CXX executable ../../../bin/test/processor_test

622[ 75%] Built target nebula_listener_test

623Scanning dependencies of target meta_http_ingest_test

624[ 75%] Building CXX object src/meta/test/CMakeFiles/meta_http_ingest_test.dir/MetaHttpIngestHandlerTest.cpp.o

625[ 75%] Linking CXX executable ../../../bin/test/meta_http_ingest_test

626[ 75%] Built target part_test

627Scanning dependencies of target authentication_test

628[ 75%] Built target multi_versions_perf_test_bm

629[ 75%] Building CXX object src/meta/test/CMakeFiles/authentication_test.dir/AuthProcessorTest.cpp.o

630[ 75%] Linking CXX executable ../../../bin/test/authentication_test

631Scanning dependencies of target cluster_id_man_test

632[ 76%] Building CXX object src/meta/test/CMakeFiles/cluster_id_man_test.dir/ClusterIdManTest.cpp.o

633[ 76%] Linking CXX executable ../../../bin/test/cluster_id_man_test

634Error: Process completed with exit code 137.
```

### CODE REVIEW

**Comment by bright-starry-sky** [comment]
Please hold this PR，stability issues still need to be analyzed

**Comment by bright-starry-sky** [comment]
Ready to review.  after running many tests, this configuration is stable

**Review by critical27 — APPROVED** [review]
Good job

**Review by panda-sheep — APPROVED** [review]
Good！

**Pull request merged**
