### PR TITLE
Fix rewrite job's time

### PR DESCRIPTION
**Pull request by laura-ding**

### CODE REVIEW

**Review by bright-starry-sky — APPROVED** [review]
LGTM

**Review by critical27 — APPROVED** [review]

**Comment by critical27** [comment]
Hold on a second.

**Comment by critical27** [comment]
In `JobDescription::jobVal` is `Status`, is this right? @liuyu85cn

**Comment by liuyu85cn** [comment]
> In `JobDescription::jobVal` is `Status`, is this right? @liuyu85cn

not that "status" :)

**Pull request merged**
