### PR TITLE
Update nebula-metad.conf.production

### PR DESCRIPTION
**Pull request by ownthink**
更改默认配置127.0.0.1

### CODE REVIEW

**Review by darionyaphet — APPROVED** [review]

**Comment by panda-sheep** [comment]
lease refer to https://github.com/vesoft-inc/nebula-storage/pull/229

This is deliberately changed in pr 229.

**Comment by bright-starry-sky** [comment]
So could you close this PR? Anyway, thank you for your contribution.

**Comment by bright-starry-sky** [comment]
Sorry, I don't know about your previous agreement with @whitewum. If it is purposeful, please reopen it.

**Comment by bright-starry-sky** [comment]
Sorry, I don't know about your previous agreement with @whitewum. If it is purposeful, please reopen it.

**Pull request closed without merging**
