### PR TITLE
Support config about index limit

### PR DESCRIPTION
**Pull request by darionyaphet**

### CODE REVIEW

**Comment by bright-starry-sky** [comment]
There is one possible scenario that we need to consider，what is the maximum number of columns supported?
The nullable bitSet(2 byte) contained in the index key, maximum of 16 columns are allowed.

**Comment by darionyaphet** [comment]
> There is one possible scenario that we need to consider，what is the maximum number of columns supported?
> The nullable bitSet(2 byte) contained in the index key, maximum of 16 columns are allowed.

skillfully

If so, The number of index columns must not be greater than the nullable column size...

**Comment by bright-starry-sky** [comment]
> > There is one possible scenario that we need to consider，what is the maximum number of columns supported?
> > The nullable bitSet(2 byte) contained in the index key, maximum of 16 columns are allowed.
> 
> skillfully
> 
> If so, The number of index columns must not be greater than the nullable column size...

Actual, columns that are nullable must be less than or equal to 16, otherwise, else we need to increase that `nullable bitSet`.
Also, for the sake of simplicity, we currently limit the column maximum to 16 without checking whether nullable.

**Comment by darionyaphet** [comment]
> > > There is one possible scenario that we need to consider，what is the maximum number of columns supported?
> > > The nullable bitSet(2 byte) contained in the index key, maximum of 16 columns are allowed.
> > 
> > 
> > skillfully
> > If so, The number of index columns must not be greater than the nullable column size...
> 
> Actual, columns that are nullable must be less than or equal to 16, else we need to increase that `nullable bitSet`.
> Also, for the sake of simplicity, we currently limit the column maximum to 16 without checking whether nullable.

It looks fine & 16 for the nullable column is enough.  I will fix the test case and avoid hard code.

**Comment by bright-starry-sky** [comment]
> > > > There is one possible scenario that we need to consider，what is the maximum number of columns supported?
> > > > The nullable bitSet(2 byte) contained in the index key, maximum of 16 columns are allowed.
> > > 
> > > 
> > > skillfully
> > > If so, The number of index columns must not be greater than the nullable column size...
> > 
> > 
> > Actual, columns that are nullable must be less than or equal to 16, else we need to increase that `nullable bitSet`.
> > Also, for the sake of simplicity, we currently limit the column maximum to 16 without checking whether nullable.
> 
> It looks fine & 16 for the nullable column is enough. I will fix the test case and avoid hard code.

👍

**Review by monadbobo — DISMISSED** [review]
LGTM.

**Review by critical27 — APPROVED** [review]
LGTM

**Review by bright-starry-sky — APPROVED** [review]
Well done.

**Pull request merged**
