### PR TITLE
Update nebula-storaged-listener.conf.production

### PR DESCRIPTION
**Pull request by cooper-lzy**

### CODE REVIEW

**Comment by whitewum** [comment]
make it consistent with doc and storage.conf

**Comment by critical27** [comment]
Is this PR ready?

**Comment by whitewum** [comment]
> Is this PR ready?

yes. just change the ports according to 2.0

**Review by bright-starry-sky — APPROVED** [review]

**Review by panda-sheep — APPROVED** [review]
Good！

**Pull request merged**
