### PR TITLE
Add header for meta response.

### PR DESCRIPTION
**Pull request by Shylock-Hg**
Require https://github.com/vesoft-inc/nebula-common/pull/348

### CODE REVIEW

**Review by dutor — APPROVED** [review]

**Comment by darionyaphet** [comment]
any benefit ?

**Comment by Shylock-Hg** [comment]
> any benefit ?

Avoid redundant code, and we could add more fields (tracing info etc.) more easily.

**Review by monadbobo — APPROVED** [review]
LGTM.

**Comment by Shylock-Hg** [comment]
Stale

**Pull request closed without merging**
