### PR TITLE
Support meta dump tool

### PR DESCRIPTION
**Pull request by darionyaphet**

### CODE REVIEW

**Comment by critical27** [comment]
@laura-ding has open a PR #134, I don't know who will do this job?

**Comment by laura-ding** [comment]
> @laura-ding has open a PR #134, I don't know who will do this job?

#134 used to upgrade the metadata from 1.0 to 2.0, this pr maybe want to print the 2.0 metadata only.

**Comment by critical27** [comment]
> > @laura-ding has open a PR #134, I don't know who will do this job?
> 
> #134 used to upgrade the metadata from 1.0 to 2.0, this pr maybe want to print the 2.0 metadata only.

Got it, 👍

**Comment by darionyaphet** [comment]
> > > @laura-ding has open a PR #134, I don't know who will do this job?
> > 
> > 
> > #134 used to upgrade the metadata from 1.0 to 2.0, this pr maybe want to print the 2.0 metadata only.
> 
> Got it, 👍

Yep  this is a simple tools to print out meta message

**Comment by critical27** [comment]
#343, closed

**Pull request closed without merging**
