### PR TITLE
Lookup distinct

### PR DESCRIPTION
**Pull request by bright-starry-sky**

### CODE REVIEW

**Comment by critical27** [comment]
Same with #230? Which one to review?

**Comment by bright-starry-sky** [comment]
> Same with #230? Which one to review?

Both are useful, this one based on #230, please review #230 first.

**Comment by bright-starry-sky** [comment]
Please hold this PR. I found a design problem from graph side. we need to have a discussion at later.

**Comment by bright-starry-sky** [comment]
close this one. other PR have done this .

**Pull request closed without merging**
