### PR TITLE
fix disk manager thread conflict

### PR DESCRIPTION
**Pull request by critical27**
Fix thread conflict when multiple thread call `addPartToPath`.

See ASAN report in https://github.com/vesoft-inc/nebula-storage/pull/508

### CODE REVIEW

**Review by panda-sheep — DISMISSED** [review]

**Review by bright-starry-sky — APPROVED** [review]
Well done.

**Comment by critical27** [comment]
Hold on a second, modify a parameter default value.

**Review by panda-sheep — APPROVED** [review]
Good！

**Review by bright-starry-sky — DISMISSED** [review]

**Comment by laura-ding** [comment]
close #514

**Comment by critical27** [comment]
Hold on one second again.....

**Review by panda-sheep — APPROVED** [review]

**Review by liuyu85cn — APPROVED** [review]

**Pull request merged**
