### PR TITLE
code improved for parameter copy

### PR DESCRIPTION
**Pull request by bright-starry-sky**
changed the parameter pass from copy to r-value ref

### CODE REVIEW

**Comment by critical27** [comment]
Maybe we could use rvalue in `asyncMultiPut` as well?

**Review by liuyu85cn — APPROVED** [review]
LGTM

**Comment by bright-starry-sky** [comment]
Please hold this PR. I need more thought. has been tested that the current changes are not effective.

**Comment by bright-starry-sky** [comment]
To strengthen again. ready to review.

**Review by critical27 — APPROVED** [review]
Good job

**Review by panda-sheep — APPROVED** [review]
Excellent!

**Pull request merged**
