### PR TITLE
Fixed rebuild index  bug

### PR DESCRIPTION
**Pull request by panda-sheep**
When one tag or one edge contains multiple indexes, wrong index data will be generated.

### CODE REVIEW

**Comment by darionyaphet** [comment]
Hold on please .Maybe I will support more interface such as rebuild specified index and rebuild all index on a tag or edge

**Comment by panda-sheep** [comment]
> interface
I do not think so
This is a defect, and incorrect index data is generated
And I will use it when rebuild index (including statistic index)

Of course, when the function is enhanced later, it can be improved

**Comment by panda-sheep** [comment]
> Hold on please .Maybe I will support more interface such as rebuild specified index and rebuild all index on a tag or edge

I do not think so
This is a defect, and incorrect index data is generated
And I will use it when rebuild index (including statistic index)
Of course, when the function is enhanced later, it can be improved

**Review by critical27 — APPROVED** [review]
Good catch!

**Comment by bright-starry-sky** [comment]
LGTM. Thanks for fixing this.

**Review by bright-starry-sky — APPROVED** [review]

**Pull request merged**
